// Server-side AI Situational Brief — replaces the prototype's client-side
// window.claude.complete call (no API key ever ships to the browser).
// Falls back to the event's static summary with a "Live analyst unavailable"
// note when ANTHROPIC_API_KEY is absent or the call fails.

import "server-only";
import Anthropic from "@anthropic-ai/sdk";
import type { CountryDTO, EventDTO } from "./repos";

const KEY = process.env.ANTHROPIC_API_KEY || "";
const MODEL = process.env.ANTHROPIC_MODEL || "claude-haiku-4-5-20251001";
const client = KEY ? new Anthropic({ apiKey: KEY }) : null;

export interface BriefResult {
  text: string;
  /** true when generated by the LLM, false when using the static fallback. */
  live: boolean;
  note?: string;
}

function buildPrompt(event: EventDTO, country: CountryDTO | null): string {
  const ctx = country
    ? ` (situation index ${country.score}/100, trend ${country.trend})`
    : "";
  return [
    "You are the analyst engine for UmmahMonitor, a live situational dashboard for the global Muslim community (the Ummah).",
    "Write a concise 2-3 sentence situational brief for the event below. Be sober, factual and analytical — like an intelligence desk note.",
    "State what is happening, the transmission path (who/what is affected next), and what to watch. No preamble, no headings, no markdown.",
    "",
    `EVENT: ${event.title}`,
    `COUNTRY: ${event.country}${ctx}`,
    `CATEGORY: ${event.category} · severity ${event.severity}`,
    `CONTEXT: ${event.what}`,
    `WHY IT MATTERS: ${event.why}`,
    `CURRENT STATUS: ${event.status}`,
  ].join("\n");
}

const FALLBACK_NOTE = "Live analyst unavailable — showing source summary.";

export async function generateBrief(
  event: EventDTO,
  country: CountryDTO | null,
): Promise<BriefResult> {
  if (!client) {
    return { text: event.what, live: false, note: FALLBACK_NOTE };
  }
  try {
    const msg = await client.messages.create({
      model: MODEL,
      max_tokens: 240,
      messages: [{ role: "user", content: buildPrompt(event, country) }],
    });
    const text = msg.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("")
      .trim();
    if (!text) return { text: event.what, live: false, note: FALLBACK_NOTE };
    return { text, live: true };
  } catch {
    return { text: event.what, live: false, note: FALLBACK_NOTE };
  }
}
